# Generated by Django 2.0.7 on 2018-07-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Representante', 'Representante'), ('Médico', 'Médico'), ('Investigador', 'Investigador')], max_length=50, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
